-- ========================================
-- AIRLINE ANALYTICS - COMPLETE SNOWFLAKE SETUP
-- Run this script in Snowflake to create all required objects
-- ========================================

-- ── Database ──
CREATE DATABASE IF NOT EXISTS AIRLINE_ANALYTICS;
USE DATABASE AIRLINE_ANALYTICS;

-- ── Schemas (medallion layers) ──
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;

-- ── Warehouse ──
CREATE WAREHOUSE IF NOT EXISTS ANALYTICS_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;

USE WAREHOUSE ANALYTICS_WH;

-- ── Raw flights table (OpenSky API ingestion target) ──
CREATE TABLE IF NOT EXISTS RAW.RAW_FLIGHTS (
    ICAO24                                  VARCHAR,
    FIRST_SEEN                              TIMESTAMP_NTZ,
    EST_DEPARTURE_AIRPORT                   VARCHAR(4),
    LAST_SEEN                               TIMESTAMP_NTZ,
    EST_ARRIVAL_AIRPORT                     VARCHAR(4),
    CALLSIGN                                VARCHAR(8),
    EST_DEPARTURE_AIRPORT_HORIZ_DISTANCE    INTEGER,
    EST_DEPARTURE_AIRPORT_VERT_DISTANCE     INTEGER,
    EST_ARRIVAL_AIRPORT_HORIZ_DISTANCE      INTEGER,
    EST_ARRIVAL_AIRPORT_VERT_DISTANCE       INTEGER,
    DEPARTURE_AIRPORT_CANDIDATES_COUNT      INTEGER,
    ARRIVAL_AIRPORT_CANDIDATES_COUNT        INTEGER,
    FLIGHT_DIRECTION                        VARCHAR(10),
    QUERIED_AIRPORT                         VARCHAR(4),
    INGESTED_AT                             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ── Grants ──
GRANT ALL PRIVILEGES ON DATABASE AIRLINE_ANALYTICS TO ROLE ACCOUNTADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE AIRLINE_ANALYTICS TO ROLE ACCOUNTADMIN;
GRANT ALL PRIVILEGES ON WAREHOUSE ANALYTICS_WH TO ROLE ACCOUNTADMIN;

-- ── Verify setup ──
SELECT 'Database' AS object, CURRENT_DATABASE() AS value
UNION ALL
SELECT 'Warehouse', CURRENT_WAREHOUSE()
UNION ALL
SELECT 'Schemas', ARRAY_TO_STRING(ARRAY_AGG(SCHEMA_NAME), ', ')
FROM INFORMATION_SCHEMA.SCHEMATA
WHERE SCHEMA_NAME IN ('RAW', 'BRONZE', 'SILVER', 'GOLD');

DESCRIBE TABLE RAW.RAW_FLIGHTS;